# Generated by Django 5.2.6 on 2026-02-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='queixa',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='triagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='triagem.triagem'),
            preserve_default=False,
        ),
    ]
