# Generated by Django 5.2.6 on 2026-02-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_remove_atendimento_queixa_atendimento_triagem'),
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='triagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triagem.triagem'),
        ),
    ]
