# Generated by Django 5.2.6 on 2026-02-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_alter_atendimento_triagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='decisao',
            field=models.CharField(blank=True, choices=[('dispensar', 'Dispensar'), ('medicacao', 'Medicação'), ('internacao', 'Internação')], max_length=20, null=True),
        ),
    ]
