# Generated by Django 6.0.2 on 2026-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_alter_atendimento_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='decisao',
            field=models.CharField(blank=True, choices=[('dispensar', 'Dispensar'), ('medicacao', 'Medicação'), ('internacao', 'Internação'), ('exames', 'Exames')], max_length=20, null=True),
        ),
    ]
