# Generated by Django 6.0.2 on 2026-02-27 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0007_alter_atendimento_decisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('pronto', 'Pronto')], default='solicitado', max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='medico.atendimento')),
            ],
        ),
    ]
