# Generated by Django 6.0.2 on 2026-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='tipo',
            field=models.CharField(choices=[('laboratorio', 'Laboratório'), ('radiologia', 'Radiologia')], default='laboratorio', max_length=20),
        ),
    ]
