# Generated by Django 6.0.2 on 2026-02-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('tecnico', 'Técnico'), ('recepcao', 'Recepção')], default='recepcao', max_length=20),
        ),
    ]
