# Generated by Django 6.0.2 on 2026-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('tecnico', 'Técnico'), ('recepcao', 'Recepção'), ('laboratorio', 'Laboratório')], default='recepcao', max_length=20),
        ),
    ]
