# Generated by Django 6.0.2 on 2026-02-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_alter_paciente_id'),
        ('recepcao', '0003_alter_agendamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(max_length=20)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frequencia_cardiaca', models.IntegerField()),
                ('saturacao', models.IntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_triagem', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcao.agendamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
