# Generated by Django 5.2.6 on 2026-02-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_alter_paciente_id'),
        ('recepcao', '0004_alter_agendamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(max_length=20)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frequencia_cardiaca', models.IntegerField()),
                ('saturacao', models.IntegerField()),
                ('atendido', models.BooleanField(default=False)),
                ('classificacao_risco', models.CharField(blank=True, choices=[('Vermelho', 'Vermelho'), ('Laranja', 'Laranja'), ('Amarelo', 'Amarelo'), ('Verde', 'Verde'), ('Azul', 'Azul')], max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_triagem', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcao.agendamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
