# Generated by Django 5.2.6 on 2026-02-18 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_alter_triagem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='enfermeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
