# Generated by Django 6.0.2 on 2026-03-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0005_alter_triagem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='entrou_fila',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='iniciou_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='tempo_espera_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
