# Generated by Django 6.0.2 on 2026-02-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacao',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
