# Generated by Django 5.2.6 on 2026-02-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_medicacao_crm_medicacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
