# Generated by Django 5.2.6 on 2026-02-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0003_alter_medicacao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicacao',
            old_name='crm',
            new_name='coren',
        ),
    ]
