# Generated by Django 6.0.2 on 2026-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0004_rename_crm_medicacao_coren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
